# Control

## Blocks
Python identifies blocks with indentation not using braces.

In [1]:
a = 0 # try it with a = 2
if a < 1:
    print('a is < than 1') # printed when if evaluates to True
    # white line do not break a block

    print('a <= than 0')   # printed when if evaluates to True
print('a is ', a)          # always printed

a is < than 1
a <= than 0
a is  0


## if-elif-else
Some data to play with:

In [1]:
ages = {'Andrea':39, 'Giuseppe':67, 'Paolo':59}

In [2]:
# names
name = 'Andrea' # try it with name = None or name = 'Unknown'
if name is None:               # test expression
    print('No name specified') # if block
elif name in ages:             # else block, test of the second if
    print(name, 'is', ages[name], 'years old')
else:                          # else of the second if
    print('Age of', name, 'is unknown')
print('Always printed')        # outside if

Andrea is 39 years old
Always printed


# while

In [4]:
count = 10
while count > 0:
    print(count,'more to go')
    count -= 1
print('done!')

10 more to go
9 more to go
8 more to go
7 more to go
6 more to go
5 more to go
4 more to go
3 more to go
2 more to go
1 more to go
done!


`continue` jumps immediately to the beginning of the loop, eventually looping again
if the loop boolean expression is `True`

`break` jumps immediately to the end of the loop.

In [5]:
a = [1, 2, 3, 4, 5, 6, 7]
while len(a)>0:         # continue jumps here
    value = a.pop()
    if value == 3:
        continue # try it with break
    print('found',value)
print('done')           # break jumps here

found 7
found 6
found 5
found 4
found 2
found 1
done


## for
`for` loops on an iterable object, assigning at each loop the value returned by the iterator
to the variable name declared are the `for` keyword

In [3]:
for letter in 'ciao':
    print(letter.upper())

C
I
A
O


## enumerate
The `enumerate` function wraps an iterator adding to its returned value an integer index.

In [4]:
for idx, name in enumerate(ages):   # equivalent to ages.keys()
    print(idx, '-', name, 'is', ages[name], 'years old')

0 - Andrea is 39 years old
1 - Giuseppe is 67 years old
2 - Paolo is 59 years old


In [5]:
for index,value in enumerate(['Pisa', 'Lucca', 'Livorno']):
    print('Value', value, 'is in position', index)

Value Pisa is in position 0
Value Lucca is in position 1
Value Livorno is in position 2


## range
The `range` function creates an iterator that returns the numbers from a start value (default: 0)
to an end value (required)
advancing by a step (default: 1)

In [6]:
for i in range(5):
    print(i)

0
1
2
3
4


In [7]:
list(range(2, 11, 2))

[2, 4, 6, 8, 10]

In [11]:
list(range(10, 1, -1))

[10, 9, 8, 7, 6, 5, 4, 3, 2]

## zip
The `zip` function merges the values returned by many iterators into a
single iterator returning tuples.
The iteration stops when one of the source iterators reachs its end, i.e.,
the number of iterated elements is equal to the shortest of the source iterators.

In [8]:
for a, s, c in zip([20,25,23], ['M','F','M'], ['PI','FI','LU']):
    print(a, s, c)

20 M PI
25 F FI
23 M LU


## Exceptions
Exceptions are severe errors that make impossible to complete a computation.

In [9]:
a = [1,2,3]
b = a[5] # 5 is out of range, which value should be assigned to 'b'? cannnot continue

IndexError: list index out of range

Sometimes you know that an operation can go wrong and you also know how to solve the problem.

The `try` statement tells the interpreter how to manage exceptions in case they happen.

In [10]:
try:             # Telling the interpreter that you know
    b = a[5]     # that something can go wrong.
except IndexError: # Telling the errors you can manage.
    b = -1       # Code to execute when the exception is raised.
b

-1

## Functions
A function defines a block of code that can be reused.
A function has a name, a list of input arguments and may return value.

In [11]:
def oldest(name_age_dict):
    """returns the name of the oldest person in the dictionary
    The dictionary must map names to ages
    """ 
    # the string above is a docstring, a human readable description of the function
    max_age = -1
    oldest_name = None
    for name in name_age_dict:
        if name_age_dict[name] > max_age:
            max_age = name_age_dict[name]
            oldest_name = name
    return oldest_name

In [12]:
help(oldest)

Help on function oldest in module __main__:

oldest(name_age_dict)
    returns the name of the oldest person in the dictionary
    The dictionary must map names to ages



In [13]:
oldest(ages)

'Giuseppe'

Input arguments take values in the same way as assignments.
You can define a default value in case an argument is not specified.

In [14]:
def oldest(name_age_dict, noname='noname'):
    """returns the name of the oldest person in the dictionary
    The dictionary must map names to ages
    """ 
    # the string above is a docstring, a human readable description of the function
    max_age = -1
    oldest_name = None
    for name in name_age_dict:
        if name_age_dict[name]>max_age:
            max_age = name_age_dict[name]
            oldest_name = name
    if oldest_name is None:
        return noname
    else:
        return oldest_name

In [15]:
help(oldest) # note the additional argument and the default value

Help on function oldest in module __main__:

oldest(name_age_dict, noname='noname')
    returns the name of the oldest person in the dictionary
    The dictionary must map names to ages



In [16]:
oldest(ages)

'Giuseppe'

In [17]:
oldest({})

'noname'

In [18]:
print('The oldest one is ' + oldest(ages)) # the function returns a string, thus I can concatenate to another string

The oldest one is Giuseppe


In [19]:
# this function modifies a mutable type (i.e., produces a side effect)
def append_one(alist):
    alist.append(1)
a = ['a']
append_one(a)
a

['a', 1]

This (useless) function creates a new object which is assigned to the local
variable, the external variable does not change.

In [20]:
def append_one(alist):
    alist = alist+[1]
a = ['a']
append_one(a)
a

['a']

This function is similar to the one above, with the difference that the new object is
returned, so that the external variable can be reassigned to it.
This is a pure function (i.e., a function without side effects).

In [21]:
def append_one(alist):
    return alist + [1]
a = ['a']
a = append_one(a)
a

['a', 1]

Another function that takes two arguments which have default values.

In [22]:
import random
def roll_dices(number_of_dices = 1, faces = 6):
    sum = 0
    for i in range(number_of_dices):
        sum += random.randint(1, faces)
    return sum

In [23]:
roll_dices()

1

In [24]:
roll_dices(2, 12)

11

If you want to use a default value for an argument and set the second one that comes after it,
explicitly use the name of the second argument.

In [25]:
roll_dices(faces=9) # rolls one dice with nine faces

9

In [26]:
def square(x):
    return x**x

In [27]:
square

<function __main__.square(x)>

Function can be assigned to variables and passed as arguments like any other object.

This function takes a function as argument
and applies it to all the elements of the first argument
returning a list with the results.

In [28]:
def apply(values, some_function):
    results = []
    for value in values:
        results.append(some_function(value)) # here the function passed as argument is applied to 'value'
    return results

Here we use `my_operation` as an argument of `apply`.

In [29]:
apply([1,2,3,4,5], square)

[1, 4, 27, 256, 3125]

# lambda functions
A lambda expression is an anonymoous function composed of a single expression. It is a object like any other function.

In [34]:
lambda x: x**2

<function __main__.<lambda>>

In [35]:
f = lambda x: x**2  # this line is equivalent to ...
f(3)

9

In [36]:
def f(x):           # ... these two
    return x**2     # lines
f(3)

9

`lambda` is useful when you need a function to be used just once in your code,
e.g., defining the sorting criteria of the `sort` function.

In [30]:
a = [('a', 5), ('b', 1), ('c', 3), ('d', 2)]
a.sort(key=lambda x: x[1], reverse=True)  # sort by the second element
a

[('a', 5), ('c', 3), ('d', 2), ('b', 1)]

# iterators
The  `for` statement implicitly uses iterators.
You can create an iterator explicitly with the `iter` function.

In [31]:
iterator = iter([0, 1, 2, 3])

In [32]:
# guess what? an iterator is an object
iterator

The `next` function returns a value from the iterator.

In [33]:
next(iterator)

0

and so on...

In [34]:
next(iterator)

1

In [35]:
next(iterator)

2

In [36]:
next(iterator)

3

Until the iterator reaches the end, then it raises a `StopIteration` exception.

In [37]:
next(iterator)

StopIteration: 

It is just a signal of the end of the iteration. You can catch it and then continue the computation.

In [38]:
a = [1, 2, 3, 4, 5]
iterator = iter(a)
while True:
    try:
        print(next(iterator))
    except StopIteration:
        print('this is the end')
        break
print('but life continues')

1
2
3
4
5
this is the end
but life continues


# generator
Generators are a way to define an iterator by means of a function that 'yields' the iterated values.

In [39]:
def infinite():
    i = 0
    while True:
        yield i # this is where the generator produces its values
        i += 1
N = infinite() # invoking the function creates the generator
N # yes, it is an object

<generator object infinite at 0x7fc93436b660>

In [40]:
next(N), next(N), next(N)

(0, 1, 2)

The functions defining generators can have arguments, just like any other function.

In [41]:
def infinite(start = 0, step = 1):
    i = start
    while True:
        yield i
        i += step
N = infinite(10, 5)
next(N), next(N), next(N)

(10, 15, 20)

# Data Structures

## Dictionaries
Dictionaries define a mapping between a set of keys and some values:
keys must be immutable,
values can be of any type.

In [42]:
population = dict() # or population = {}
population['pisa'] = 91104
population['livorno'] = 160027
population

{'pisa': 91104, 'livorno': 160027}

In [43]:
population['pisa'] # get value from key

91104

In [44]:
'firenze' in population # check if key exists

False

In [45]:
population['firenze'] # exception is raised if key does not exist

KeyError: 'firenze'

Use get to fail gracefully with a default value:

In [46]:
population.get('firenze', -1) 

-1

In [47]:
population.get('pisa',-1)

91104

keys are unique, reassigning replaces value

In [48]:
population['pisa'] = 10000000 
population['pisa']

10000000

Remove keys with `del`

In [49]:
del population['livorno']
population['livorno']

KeyError: 'livorno'

In [50]:
ages = {'Andrea': 39, 'Giuseppe': 67, 'Paolo': 58}

The keys, values, and items methods returns objects that act as list views on the keys, 
values, and key-value pairs in the dictionary

In [51]:
keys = ages.keys()
values = ages.values()
items = ages.items()

In [52]:
keys

dict_keys(['Andrea', 'Giuseppe', 'Paolo'])

In [53]:
values

dict_values([39, 67, 58])

In [54]:
items

dict_items([('Andrea', 39), ('Giuseppe', 67), ('Paolo', 58)])

As they are views, they cannot be changed, but they change as the dictionary changes

In [55]:
ages['Fabrizio'] = 42

In [56]:
keys

dict_keys(['Andrea', 'Giuseppe', 'Paolo', 'Fabrizio'])

## List comprehensions 

In [57]:
a = list()
for x in range(6):
    a.append(x**2)

The above `for` loop can be expressed in a more compact and math-like way, as a list comprehension.

In [58]:
a = [x**2 for x in range(6)]

In [59]:
a = list()
for x in range(6):
    if x%2 == 0: # filtering condition
        a.append(x**2)

The filtering condition can be added at the end of the statement.

In [61]:
a = [x**2 for x in range(6) if x%2 == 0]
a

[0, 4, 16]

Nested loops.

In [62]:
text = ['never', 'gonna', 'give', 'you', 'up']
output = list()
for word in text:
    for char in word:
        output.append(char)
output

['n',
 'e',
 'v',
 'e',
 'r',
 'g',
 'o',
 'n',
 'n',
 'a',
 'g',
 'i',
 'v',
 'e',
 'y',
 'o',
 'u',
 'u',
 'p']

Nested loops can be converted into nested list comprehensions.

In [54]:
[char for word in text for char in word ]

['n',
 'e',
 'v',
 'e',
 'r',
 'g',
 'o',
 'n',
 'n',
 'a',
 'g',
 'i',
 'v',
 'e',
 'y',
 'o',
 'u',
 'u',
 'p']

List comprehesion generates a complete list.
Using it on an infitine generator will run for long (stop it with the <i class="fa fa-stop"></i> button) and eventually will cause a memory error.

In [15]:
even = [x for x in infinite() if x%2 == 0]

KeyboardInterrupt: 

Using parentheses instead of square brackets produces a generator.
Generators use lazy evaluation, so they do not have problems with
infinite sequences.

In [63]:
even = (x for x in infinite() if x%2 == 0)
next(even), next(even), next(even)

(0, 2, 4)

## Classes
A class wraps in a single entity a state, defined by a set of variables (fields),
and functions to operate on that state (methods).

In [57]:
class Person:
    def __init__(self, name, age): # constructor
        self.name = name          # instance variables
        self.age = age            # self is like 'this' in Java, C#
    
    def young(self):              # method that return a value
        return self.age < 40
    
    def birthday(self):           # method that changes the state
        self.age += 1             # of the object

The method `__init__` is invoked when an object is constructed.

In [58]:
me = Person('Andrea', 39)

In [59]:
me.young()

True

Why there is `self` in methods?

`self` is a reference to the instance of the object, similar to 'this' in C++, Java, C#

Differently from those languages, in Python 'self' must be explicitly used.
When you write `me.young()`, `me` is passed automatically as `self` to the method of the class.

In fact you can invoke methods of a class using this equivalent notation:

In [60]:
Person.young(me)

True

You can... but almost no one actually using this syntax.
It is just good to know it.

### Class variables
classes can have class-wise variables (somewhat like 'static' in Java)

In [61]:
class Person():
    population = 0                # class variable
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        Person.population += 1    # incremented when created

    def young(self):    
        return self.age < 40
    
    def birthday(self):         
        self.age += 1   
    
    def __del__(self):
        Person.population -=1     # decremented when created


In [62]:
# we use this function to play with class inheritance
def is_young(some_person):
    if some_person.young():
        print(some_person.name, 'is a young person')
    else:
        print(some_person.name, 'was a young person')

In [63]:
me = Person('Andrea', 39)
is_young(me) # <40 -> young

Andrea is a young person


In [64]:
me.birthday() # 40!
is_young(me) # ==40 -> not young

Andrea was a young person


### Inheritance
When defining a class you can specify one or more base classes from which
the new class inherits methods and any class level field.
Any method with the same name of a base class methods hides that base class method.

In [65]:
class Researcher(Person):
    def __init__(self, name, age, discipline):
        super().__init__(name, age) # the super method gives access to base class methods
        self.discipline = discipline

    def young(self): # a researcher is always young because is always learns new things
        return True

In [66]:
me = Researcher('Andrea', 39, 'Machine Learning')
me.birthday()
me.young() # :)

True

# I/O
The `input` function stops the interpreter and reads a line from the console.

In [67]:
people = list()
while True:
    name = input('name? ')
    age = int(input('age? '))
    people.append(Person(name, age))
    stop_check = input("enter 'x' to stop creating persons ")
    if stop_check == 'x':
        break
print(people)

name? Andrea
age? 39
enter 'x' to stop creating persons 
name? Giuseppe
age? 67
enter 'x' to stop creating persons 
name? Paolo
age? 59
enter 'x' to stop creating persons x
[<__main__.Person object at 0x000001B4EFE4B390>, <__main__.Person object at 0x000001B4EFE4BC50>, <__main__.Person object at 0x000001B4EFD76518>]


The `open` function is used to open file both for writing and/or reading,
either in text format or in binary format.
The default is reading a text file.

Let's open a text file and write two lines in it.

In [68]:
file = open('filename.txt', mode='w', encoding='utf-8')
file.write('ciao\n')   # newlines are not added automatically
file.write('hello\n')
file.close()           # remember to close files

now open the same file to read back from it.

In [69]:
file = open('filename.txt', encoding='utf-8')
print(next(file))          # a text file object acts as a iterator over lines

ciao



In [70]:
print(next(file))

hello



In [71]:
file.close() # rember to close

Better than remembering to close a file is having the file closed automatically
when you don't need it no more, by using the `with` statement.

In this case the file is closed even when an uncatched exception happens.

In [72]:
with open('filename.txt', mode='w', encoding='utf-8') as file:
    file.write('ciao\n')
    file.write('hello\n')

In [73]:
with open('filename.txt', encoding='utf-8') as file:
    for line in file:
        print(line)

ciao

hello



You can read a whole text file in a single string using the `read()` method.

**Not recommended**, except for short files.

In [74]:
with open('filename.txt', encoding='utf-8') as file:
    text = file.read()
text

'ciao\nhello\n'

Files in comma separated value (CSV) format are useful to store tabular data.

In [75]:
import csv
data = [['Andrea', 39], ['Giuseppe', 67], ['Paolo', 59]]
with open('data.csv', mode='w', encoding='utf-8', newline='') as outfile:
    writer = csv.writer(outfile) # once you open the file you wrap it with a csv.writer or a csv.reader
    writer.writerows(data) # then you can write rows in a single shot...
    
    # or a row at a time
    for row in data:
        writer.writerow(row)

In [76]:
import csv
data = list()
with open('data.csv', encoding='utf-8', newline='') as infile:
    reader = csv.reader(infile)
    for row in reader:
        data.append([row[0],int(row[1])])
data # data is duplicate beacuse we wrote it twice in the previous cell

[['Andrea', 39],
 ['Giuseppe', 67],
 ['Paolo', 59],
 ['Andrea', 39],
 ['Giuseppe', 67],
 ['Paolo', 59]]

## pickle
The `pickle` module implements binary serialization of python objects.
Note that file are openend as binary streams, not text.

In [146]:
import pickle
with open('data.pkl', mode='wb') as file:
    pickle.dump(data, file)

In [148]:
with open('data.pkl', mode='rb') as file:
    data2 = pickle.load(file)
data2

[['Andrea', 39],
 ['Giuseppe', 67],
 ['Paolo', 59],
 ['Andrea', 39],
 ['Giuseppe', 67],
 ['Paolo', 59]]

## NumPy
NumPy is a Python library, which adds support for large, multi-dimensional arrays and matrices, along with a large collection of optimized, high-level mathematical functions to operate on these arrays.

In [65]:
# Import numpy
import numpy as np

In [66]:
# Create numpy arrays from lists
x = np.array([1,2,3]) 
y = np.array([[3,4,5]]) 
z = np.array([[6,7],[8,9]])

# Let's take a look at their shapes.
# When working with numpy arrays, .shape will be a very useful debugging tool 
print(x.shape)
print(y.shape)
print(z.shape)

(3,)
(1, 3)
(2, 2)


Vectors can be represented as 1-D arrays of shape (N,) or 2-D arrays of shape (N, 1) or (1, N). But it's important to note that the shapes (N,), (N, 1), and (1,N) are not the same and may result in different behavior (we'll see some examples below involving matrix multiplication and broadcasting).

Matrices are generally represented as 2-D arrays of shape (M, N).

The best way to ensure your code gives you the behavior you expect is to keep track of your array shapes and try out small test cases or refer back to documentation when you are unsure.

### Array Operations

There are many NumPy operations that can be used to reduce a numpy array along an axis.

Let's look at the np.max operation (documentation: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html).

In [68]:
x = np.array([[1,2],[3,4], [5, 6]]) 

In [71]:
np.max(x)

6

In [69]:
print(np.max(x, axis = 1))

[2 4 6]


In [70]:
np.max(x, axis = 1, keepdims = True)

array([[2],
       [4],
       [6]])

Next, let's look at some matrix operations. Let's take an element-wise product (Hadamard product).

In [72]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 3], [3, 3]])
print(A)
print(B)
print("---")
print(A * B)

[[1 2]
 [3 4]]
[[3 3]
 [3 3]]
---
[[ 3  6]
 [ 9 12]]


We can do matrix multiplication with `np.matmul` or `@`.

In [73]:
# One way to do matrix multiplication
print(np.matmul(A, B))

# Another way to do matrix multiplication
print(A @ B)

[[ 9  9]
 [21 21]]
[[ 9  9]
 [21 21]]


We can take the dot product or a matrix vector product with `np.dot`. 

In [74]:
u = np.array([1, 2, 3])
v = np.array([1, 10, 100])

print(np.dot(u, v))

# Can also call numpy operations on the numpy array, useful for chaining together multiple operations
u.dot(v)

321


321

In [75]:
W = np.array([[1, 2], [3, 4], [5, 6]])
print(v.shape)
print(W.shape)

# This works.
print(np.dot(v, W))
print(np.dot(v, W).shape)

(3,)
(3, 2)
[531 642]
(2,)


In [76]:
# This does not. Why?
np.dot(W, v)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [77]:
# We can fix the above issue by transposing W.
print(np.dot(W.T, v))
print(np.dot(W.T, v).shape)

[531 642]
(2,)


###  Indexing

Slicing / indexing numpy arrays is a extension of the Python concept of slicing (lists) to N dimensions.

In [78]:
x = np.random.random((3, 4))

# Selects all of x
x[:]

array([[0.90985881, 0.29998899, 0.04102125, 0.51444207],
       [0.23622129, 0.59258436, 0.84285452, 0.7296502 ],
       [0.14081926, 0.02532328, 0.35182874, 0.23490826]])

Selects the 0th and 2nd rows 

In [79]:
print(x[np.array([0, 2]), :])

print("---")

# Selects 1st row as 1-D vector and and 1st through 2nd elements
print(x[1, 1:3])

[[0.90985881 0.29998899 0.04102125 0.51444207]
 [0.14081926 0.02532328 0.35182874 0.23490826]]
---
[0.59258436 0.84285452]


In [82]:
x[:-1]

array([[0.90985881, 0.29998899, 0.04102125, 0.51444207],
       [0.23622129, 0.59258436, 0.84285452, 0.7296502 ]])

Boolean indexing

In [80]:
x[x > 0.5]

array([0.90985881, 0.51444207, 0.59258436, 0.84285452, 0.7296502 ])

3-D vector of shape (3, 4, 1)

In [81]:
x[:, :, np.newaxis]

array([[[0.90985881],
        [0.29998899],
        [0.04102125],
        [0.51444207]],

       [[0.23622129],
        [0.59258436],
        [0.84285452],
        [0.7296502 ]],

       [[0.14081926],
        [0.02532328],
        [0.35182874],
        [0.23490826]]])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

**General Broadcasting Rules**

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when:
- they are equal, or
- one of them is 1 (in which case, elements on the axis are repeated along the dimension)

More details: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [83]:
x = np.random.random((3, 4))
y = np.random.random((3, 1))
z = np.random.random((1, 4))

# In this example, y and z are broadcasted to match the shape of x. 
# y is broadcasted along dim 1.
s = x + y
# z is broadcasted along dim 0.
p = x * z

In [84]:
print(x.shape)
print(y.shape)
print(s.shape)

(3, 4)
(3, 1)
(3, 4)


In [85]:
print(x.shape)
print(z.shape)
print(p.shape)

(3, 4)
(1, 4)
(3, 4)


Let's look at a more complex example.

In [86]:
a = np.random.random((3, 4))
b = np.random.random((3, 1))
c = np.random.random((3, ))

What is the expected broadcasting behavior for these operations? What do the following operations give us? What are the resulting shapes?

In [44]:
result1 = b + b.T

print(b.shape)
print(b.T.shape)
print(result1.shape)
print(result1)

(3, 1)
(1, 3)
(3, 3)
[[1.5683191  1.32822013 1.16548899]
 [1.32822013 1.08812117 0.92539003]
 [1.16548899 0.92539003 0.76265888]]


In [45]:
result2 = a + c

print(a.shape)
print(c.shape)
print(result2.shape)
print(result2)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [46]:
result3 = b + c

print(b.shape)
print(c.shape)
print(result3.shape)
print(result3)

(3, 1)
(3,)
(3, 3)
[[1.7830505  0.91483839 1.21397415]
 [1.54295154 0.67473942 0.97387519]
 [1.3802204  0.51200828 0.81114405]]


### Efficient NumPy Code

When working with numpy arrays, avoid explicit for-loops over indices/axes at all costs. For-loops will dramatically slow down your code (~10-100x).

We can time code using the %%timeit magic. Let's compare using explicit for-loop vs. using numpy operations.

In [87]:
%%timeit
x = np.random.rand(1000, 1000)
for i in range(100, 1000):
    for j in range(x.shape[1]): 
        x[i, j] += 5

410 ms ± 4.28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [88]:
%%timeit
x = np.random.rand(1000, 1000)
x[np.arange(100,1000), :] += 5 

10.6 ms ± 181 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
